name: 'Build Docker Image'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: string
        default: 'build'
  schedule:
    - cron: '0 12 1 * *'
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "root/**"
      - "Dockerfile"
  push:
    branches:
      - nightly
    paths:
      - ".github/workflows/build.yml"
      - "root/**"
      - "Dockerfile"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.branch || 'build' }}
  cancel-in-progress: true

env:
  FRAMEWORK: net8.0
  BRANCH_TO_BUILD: ${{ inputs.branch || 'build' }}

jobs:
  prepare:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.version }}
      branch: ${{ steps.variables.outputs.branch }}
      tag_branch: ${{ steps.variables.outputs.tag_branch }}
    env:
      RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Retrieving external version
        id: ext_release
        run: |
          EXT_RELEASE=$(curl -sL "https://radarr.servarr.com/v1/update/nightly/changes?runtime=netcore&os=linuxmusl" | jq -r '.[0].version')
          if [ -z "${EXT_RELEASE}" ] || [ "${EXT_RELEASE}" == "null" ]; then
            echo "**** Can't retrieve external version, exiting ****"
            echo "Can't retrieve external version, exiting" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          EXT_RELEASE=$(echo ${EXT_RELEASE} | sed 's/[~,%@+;:/]//g')
          echo "**** External version: ${EXT_RELEASE} ****"
          echo "External version: ${EXT_RELEASE}" >> $GITHUB_STEP_SUMMARY
          echo "VERSION=${EXT_RELEASE}" >> $GITHUB_ENV
          if [[ "${EXT_RELEASE}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)$ ]]; then
            SEMVER="${BASH_REMATCH[1]}"
            echo "**** Semantic version: ${SEMVER} ****"
            echo "Semantic version: ${SEMVER}" >> $GITHUB_STEP_SUMMARY
            echo "SEMVER=${SEMVER}" >> $GITHUB_ENV
          else
            echo "**** Can't parse semantic version, exiting ****"
            exit 2
          fi

      - name: Setup Environment Variables
        id: variables
        shell: bash
        run: |
          echo "version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
          echo "branch=${RAW_BRANCH_NAME//\//-}" >> "$GITHUB_OUTPUT"
          echo "tag_branch=${{ env.BRANCH_TO_BUILD }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

  backend:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        runtime:
          - linux-musl-x64
          - linux-x64
          - osx-x64
        branch:
          - ${{ inputs.branch || 'build' }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      BUILD_SOURCEBRANCHNAME: develop
    steps:
      - name: Check out
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ github.repository_owner }}/Radarr
          ref: ${{ matrix.branch }}

      - uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '8.0.x'

      - run: dotnet --info

      - name: Setup Environment Variables
        run: |
          echo "RADARRVERSION=${{ needs.prepare.outputs.version }}" >> "$GITHUB_ENV"

      - name: Build Backend
        run: |
          ./build.sh --backend -f "${{ env.FRAMEWORK }}" -r "${{ matrix.runtime }}"

      - name: Package
        run: |
          sed -i '/cp -r \$outputFolder\/UI \$folder/d' build.sh
          ./build.sh --packages -f "${{ env.FRAMEWORK }}" -r "${{ matrix.runtime }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-${{ matrix.runtime }}
          path: _artifacts/**/*
          retention-days: 1
          if-no-files-found: error

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          repository: ${{ github.repository_owner }}/Radarr
          ref: ${{ env.BRANCH_TO_BUILD }}

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'

      - name: Yarn Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Stylelint
        run: yarn stylelint "frontend/**/*.css" --config frontend/.stylelintrc -f github

      - name: Build
        run: yarn build --env production

      - name: Publish UI Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build_ui
          path: _output/UI/**/*
          retention-days: 1
          if-no-files-found: error

  package:
    needs:
      [
        prepare,
        backend,
        frontend,
      ]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        runtime:
          - linux-musl-x64
          - linux-x64
          - osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: build-${{ matrix.runtime }}
          path: _output

      - name: Download UI Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: build_ui
          path: _output/UI

      - name: Create Packages
        run: |
          ./build.sh --packages -f net8.0 -r linux-musl-x64
          rm -rf _artifacts/linux-musl-x64/net8.0/Radarr/Radarr.Update
          find . -name "Radarr" -exec chmod a+x {} \;
          find . -name "ffprobe" -exec chmod a+x {} \;

#      - name: Build Package
#        working-directory: build
#        run: |
#          ./build.sh --packages -f net8.0 -r linux-musl-x64
#          rm -rf _artifacts/linux-musl-x64/net8.0/Radarr/Radarr.Update
#          find . -name "Radarr" -exec chmod a+x {} \;
#          find . -name "ffprobe" -exec chmod a+x {} \;
#
#      - name: Docker meta
#        id: docker_meta
#        uses: docker/metadata-action@v5.8.0
#        with:
#          images: |
#            ghcr.io/${{ github.repository_owner }}/radarr
#          labels: |
#            org.opencontainers.image.authors=${{ github.repository_owner }}
#            org.opencontainers.image.vendor=${{ github.repository_owner }}
#            build_version=${{ env.RADARRVERSION }}
#          tags: |
#            type=raw,value=${{ env.BRANCH }}-${{ env.RADARRVERSION }},enable=${{ github.event_name != 'pull_request' && (github.ref_name != 'master' && github.ref_name != 'main') && env.BRANCH_TO_BUILD == 'build' }}
#            type=raw,value=${{ env.RADARRVERSION }},enable=${{ github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'main') && env.BRANCH_TO_BUILD == 'build' }}
#            type=raw,value=${{ env.BRANCH }}-${{ env.SEMVER }},enable=${{ github.event_name != 'pull_request' && (github.ref_name != 'master' && github.ref_name != 'main') && env.BRANCH_TO_BUILD == 'build' }}
#            type=raw,value=${{ env.SEMVER }},enable=${{ github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'main') && env.BRANCH_TO_BUILD == 'build' }}
#            type=raw,value=${{ env.BRANCH }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD == 'build' }}
#            type=raw,value=${{ steps.gen_meta.outputs.tag_branch }}-${{ env.RADARRVERSION }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD != 'build' }}
#            type=raw,value=branch-${{ steps.gen_meta.outputs.tag_branch }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD != 'build' }}
#            type=ref,event=pr
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3.11.1
#        with:
#          platforms: linux/amd64
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3.4.0
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v6.18.0
#        with:
#          context: .
#          push: true
#          platforms: linux/amd64
#          tags: ${{ steps.docker_meta.outputs.tags }}
#          labels: ${{ steps.docker_meta.outputs.labels }}
#          build-args: |
#            VERSION=${{ env.RADARRVERSION }}-${{ env.BRANCH }}-r${{ github.run_number }}
